#%RAML 1.0 DataType
  properties:
    libraryCode:
      type: string
      required: true
      description: library Code
    libraryBranch:
      type: string
      required: false
      description: library Branch
  example:
        {
  "libraryCode": "IB213",
  "libraryBranch": "Hyderabad"
        }