#%RAML 1.0 DataType
properties:
                libraryCode:
                  type: string
                  required: true
                  example:
                    "IBS123"
                address:
                  type: string
                  required: true
                  example:
                    "hyderabad"
                phoneNumber:
                  type: integer
                  example:
                    8765423456
                emailAddress:
                  type: string
                  required: true
                  example:
                    "klart@gmail.com"