#%RAML 1.0 DataType
properties:
          libraryCode:
            type: string
            example:
              "IBS123"
          title:
            type: string
            example:
              "Half Girlfriend"
          author:
            type: string
            example:
              "Chetan Bhagat"