#%RAML 1.0 NamedExample
example to get the book info:
  {
  "libraryCode": "IBS123",
    "books":[{
      "bookCode": "BS1234",
      "Title": "romcom",
      "author": "Bhagat",
      "book categoery": "Tech",
      "Read Tinein Hours": 36,
      "rating": "4",
      "rental price": 50,
      "best seller": "YES"
         },
        {
      "bookCode": "BS5678",
       "Title": "Mythology",
       "author": "someone",
      "book categoery": "science",
      "Read Tinein Hours": 36,
      "rating": "5",
      "rental price": 60,
      "best seller": "YES"
            }
            ]
    }